### ISSUE TITLE
Copying text from generated pdf's buggy

### ISSUE THREAD

**Issue by hur** [RunasSudo/gfx2gfx-pdftext#3]
After compiling some pdf's, I ran into an error with text copying. Before the invisible text -fix, text was still copiable and would paste properly. Currently, trying to highlight text from the generated pdf's doesn't work properly. 
![git](https://cloud.githubusercontent.com/assets/4998544/20629285/5c78ffac-b333-11e6-8dad-a2ad60c1509e.png)
I only highlighted the word 'dream' but as the picture shows, more words are highlighted. Pasting this results in a mess of incoherency:
![git2](https://cloud.githubusercontent.com/assets/4998544/20629310/7d1e5284-b333-11e6-8c4a-3aa19d1ac023.png)

Additional details:
I used parameter -r 300
Tested in Adobe Reader and Google Drive

**Comment by hur** [comment]
Can't reproduce it myself even, may have been just a bug.
EDIT:  Also read the other closed issue so this one was pointless.

**Comment by TheRandomLabs** [comment]
I'm experiencing the same issue:
![image](https://user-images.githubusercontent.com/16755704/56845320-bd66e900-6902-11e9-8520-4a28bf4e1fb2.png)
