### ISSUE TITLE
Regression: Image positioning broken

### ISSUE THREAD

**Issue by andrewcchen** [RunasSudo/gfx2gfx-pdftext#5]
Images are not positioned properly in latest commit (2a84c79535c136e08d056c4904f7bfb888ffa368), while they were in upstream (c40abbf854502f2430403a188ac8b1b431be6e86).

Offending swf: [swf.zip](https://github.com/RunasSudo/gfx2gfx-pdftext/files/614594/swf.zip)

**Comment by andrewcchen** [comment]
Wow that was fast :)

**Comment by RunasSudo** [comment]
*No sleep. **Only code.***

jk I had nothing to do when I saw the email notification come through, and I had a fair idea of what the problem was. Have a nice day!

**Comment by andrewcchen** [comment]
Haha. Thanks. You too! :)

Meanwhile, I should be preparing my English A IOP (it's next week :( ), yet I'm here procrastinating on reddit and github...
